### ISSUE TITLE
UDP protocol not supported by ELB created by 'Docker for AWS'

### ISSUE THREAD

**Issue by shazChaudhry** [docker/for-aws#107]
### Expected behavior
Messages sent by docker services (_running outside AWS_) using GELF logging driver reach a Logstash instance deployed in a 'Docker for AWS' cluster via AWS ELB

### Actual behavior
Logstash deployed in a  'Docker for AWS' cluster does not receive messages via AWS ELB as AWS ELB is not listening on the UDP protocol. 

### Information
During a google search for a possible resolution, I have come across these articles suggesting AWS ELB does not support the UDP protocole:
- https://forums.aws.amazon.com/message.jspa?messageID=717368
- https://www.sumologic.com/blog/using-sumo/aws-elb-3-things-to-know/

Here is a snippet of my service compose file that I execute on my local machine:
```
    jenkins:
        image: jenkins/jenkins
        logging:
            driver: gelf
            options:
                gelf-address: udp://127.0.0.1:12201
```
Here is a snippet of my Logstash compose file that I execute on a cluster created by 'Docker for AWS':
```
    logstash:
        image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION:-5.6.2}
        ports:
          - "12201:12201/udp"
```

### Steps to reproduce the behavior
- Launch a cluster of 3 managers and 5 workser (_t2.large_) via https://console.aws.amazon.com/cloudformation/home#/stacks/new?stackName=Docker&templateURL=https://editions-us-east-1.s3.amazonaws.com/aws/stable/Docker.tmpl
- SSH into a master node
- git clone https://github.com/shazChaudhry/elastic.git && cd elastic
- ELASTIC_VERSION=5.6.2 docker stack deploy -c docker-compose.yml elastic
- Elastic stack starts up
- Over on the Load Balancers page; listener tab, I do not see a UDP port 12201

How do I send UDP messages to a service running inside a 'Docker for AWS' cluster via AWS ELB please? I would really appreciate any suggestion.
