### ISSUE TITLE
Use Amazon EFS as Volume

### ISSUE THREAD

**Issue by zyph00** [docker/for-aws#119]
### Expected behavior
I'm trying to use the Amazon AWS EFS as volume.

My docker-compose.yml looks like this:

```
version: '3'

services:
  pimcore-jcii:
    image: {SECRET}/pimcore5:current
    ports:
      - "8000:80"
    volumes:
      - efs-pimcore:/data
    deploy:
      mode: replicated
      replicas: 1

volumes:
  efs-pimcore:
    driver: "cloudstor:aws"
```

### Actual behavior
The docker container has the current state "Rejected" and I get the following error message:
`"create pim_efs-pimcore: VolumeDriver.Create: volume creation failed: Invalid volume size: strconv.ParseInt: parsing "": invalid syntax"  `

Where is the problem? Isn't this possbile to do it like that?

**Comment by FrenchBen** [comment]
Did you make sure to enable EFS support during your stack deployment?
![efs-enable](https://user-images.githubusercontent.com/3965324/32865015-325d880a-ca16-11e7-83cf-ff9afdb6d739.png)

**Comment by ddebroy** [comment]
FrenchBen's suggestion above is correct. I would recommend adding the following to the compose file to get a more accurate error:

```
volumes:
  efs-pimcore:
    driver: cloudstor:aws
    driver_opts:
      backing: shared
```

Error with EFS pre-req creation disabled and modified compose file:
```
"Err": "create stack10_efs-pimcore: VolumeDriver.Create: EFS support necessary for backing type: \"shared\""
```

In the absence of an explicitly specified `backing` and creation of EFS pre-reqs disabled, cloudstor defaults to EBS/`relocatable` volumes and complains about lack of expected parameters.
