### ISSUE TITLE
Manually created volume snapshots get deleted

### ISSUE THREAD

**Issue by sfrese** [docker/for-aws#122]
### Expected behavior
It should be possible to manually create snapshots of EBS volumes managed by CloudStor without them getting deleted over time.

### Actual behavior
When manually creating a snapshot of an EBS volume that has been created by CloudStor, it's being deleted after ~15 minutes.

### Information

I tested the behaviour with templates based on 17.06.2-ce and 17.09.0-ce and the following compose setup:

```
version: '3'

services:
  db:
    image: postgres:9.4
    volumes:
      - cloudstor-ebs-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/db-files/
    deploy:
      placement:
        constraints: [node.role == worker]
volumes:
  cloudstor-ebs-volume:
    driver: cloudstor:aws
    driver_opts:
      backing: relocatable
      size: 4
      ebstype: gp2
```

I dug a bit deeper and found the following event of the snapshot's deletion which has been issued by one of the worker nodes.

```
{
   "eventVersion":"1.05",
   "userIdentity":{
      "type":"AssumedRole",
      "principalId":"AROAI4YFOR4EWVHKYJ3YW:i-0d1c416fde2da3248",
      "arn":"arn:aws:sts::286248583856:assumed-role/cloudstorDeleteTest-WorkerRole-EI5JVZ92E06D/i-0d1c416fde2da3248",
      "accountId":"286248583856",
      "accessKeyId":"xxx",
      "sessionContext":{
         "attributes":{
            "mfaAuthenticated":"false",
            "creationDate":"2017-11-23T09:06:17Z"
         },
         "sessionIssuer":{
            "type":"Role",
            "principalId":"AROAI4YFOR4EWVHKYJ3YW",
            "arn":"arn:aws:iam::286248583856:role/cloudstorDeleteTest-WorkerRole-EI5JVZ92E06D",
            "accountId":"286248583856",
            "userName":"cloudstorDeleteTest-WorkerRole-EI5JVZ92E06D"
         }
      }
   },
   "eventTime":"2017-11-23T11:39:31Z",
   "eventSource":"ec2.amazonaws.com",
   "eventName":"DeleteSnapshot",
   "awsRegion":"eu-west-1",
   "sourceIPAddress":"52.30.180.118",
   "userAgent":"aws-sdk-go/1.8.22 (go1.7.6; linux; amd64)",
   "requestParameters":{
      "snapshotId":"snap-0dae7cc12c7c7ab3b",
      "force":false
   },
   "responseElements":{
      "_return":true
   },
   "requestID":"41876da2-2222-43b7-be8f-96603ba3e8b3",
   "eventID":"527eecd8-41d6-407d-a567-d470ae12a16a",
   "eventType":"AwsApiCall",
   "recipientAccountId":"286248583856"
}
```

### Steps to reproduce the behavior

1. Deploy a fresh swarm from the cloudformation template
2. Deploy a new docker stack based on the given compose file
3. Create a manual snapshot of the abs volume that cloudstor created using AWS management console or sdk
4. Wait ~15mins
5. Cloudstor will have deleted the manual snapshot and only snapshots created by cloudstor from 5 and 10 minutes ago remain.
