### ISSUE TITLE
Cloudstor Volume on D4AWS not mounting to worker nodes correctly

### ISSUE THREAD

**Issue by hierozbosch** [docker/for-aws#143]
### Expected behavior

Nodes on a swarm should mount a Cloudstor named volume with same volume content on all nodes.

### Actual behavior

Worker nodes mount the volume without error, but the volume contents are different on different nodes.

### Information

I recently brought a stack down via docker stack rm.  This stack has been running for about 6 months--pretty stable (thanks, d4aws).  The compose file has not changed.

COMPOSE FILE:
```
version: "3.2"
services:
  neo4j:
    image: neo4j:3.2.1
    environment:
      - HOME=/root
      - NEO4J_AUTH=none
      - NEO4J_dbms_memory_pagecache_size=100M
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=2G
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - gc01_data:/data
      - gc01_neo4j_logs:/logs
    networks:
      - backend
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      replicas: 1
      placement:
        constraints: [engine.labels.node_task == neo4j]
      restart_policy:
        condition: on-failure

     ... other services...

secrets:
  gcrt_cert:
    external: true
  gcrt_key:
    external: true

networks:
  frontend:
  backend:

volumes:
  nmod_core:
  gc01_neo4j_logs:
  gc01_data:
    external: true
```

But there was one thing I did different:  When it was down I mounted the Cloudstor volume (gc01_data) to a new container via:
```
~ $ docker run -it -d -v gc01_data:/data 184dead443cd sh
```
Mounting the volume was actually not necessary, since the container was using a driver to talk to the db.  So in fact the container's task never read or wrote to the volume.

When I launched the full stack again via docker stack deploy, using the compose file above, the stack deployed without error.  But the Cloudstor volume where the database was stored did not mount correctly on the worker node where the database service was running.  

Comparing the 2 nodes after deployment I found:

AFTER DEPLOYMENT, on MANAGER NODE:

```
~ $ docker volume ls
DRIVER              VOLUME NAME
cloudstor:aws       gc01_data
local               mydb
local               sshkey
~ $ docker volume inspect gc01_data
[
    {
        "Driver": "cloudstor:aws",
        "Labels": {},
        "Mountpoint": "/mnt/ebs/gc01_data",
        "Name": "gc01_data",
        "Options": {
            "backing": "relocatable",
            "ebstype": "gp2",
            "size": "25"
        },
        "Scope": "local"
    }
]
```

NOTE THAT THE DATABASE ON THE VOLUME CONTAINS DATA (391688 blks):
```
~ $ docker run -it -d -v gc01_data:/data alpine:latest
cc34870349b81e70c2539ce263f03a78000e7e3696470a66d8c701105b3ed833
~ $ docker exec -it cc34870349b8 sh
/ # du -d 1 /data/databases/graph.db
4	/data/databases/graph.db/schema
4	/data/databases/graph.db/index
391688	/data/databases/graph.db
```

BUT ON THE WORKER NODE:
```
~ $ ssh -A 172.31.8.16
Welcome to Docker!
~ $ docker volume ls
DRIVER              VOLUME NAME
local               1a102090dab5c86ade898a545bede71e657959f811c1fc5480a1d70dbe4a2929
cloudstor:aws       gc01_data
local               gcrt_stack_gc01_neo4j_logs
local               sshkey
~ $ docker volume inspect gc01_data
[
    {
        "Driver": "cloudstor:aws",
        "Labels": null,
        "Mountpoint": "/mnt/ebs/gc01_data",
        "Name": "gc01_data",
        "Options": {},
        "Scope": "local"
    }
]
```

NOTE THE DATABASE VOLUME IS EMPTY (212 BLKS):
```
~ $ docker run -it -d -v gc01_data:/data alpine:latest /bin/sh
ece9a2790db458249b275861d068de046c7c36b84d07ab105f2e0ee84e7d1b74
~ $ docker exec -it ece9a2790db458 /bin/sh
/ # du -d 1 /data/databases/graph.db
4	/data/databases/graph.db/index
212	/data/databases/graph.db
```
Actually it appears that the database set up a default empty database when it launched, as it would do if it found its data directory empty.

Both nodes seem to be mounting a Cloudstor volume named "gc01_data."  The options are different, but set Scope: 'local' on both, so I'm guessing it's not the same volume, but it's called the same.

I guess my next step would be to `docker volume rm gc01_data`, but thought I'd check in with y'all before taking that ride.

Thanks
