### ISSUE TITLE
Share EFS-stored volumes beetween stacks

### ISSUE THREAD

**Issue by daaru00** [docker/for-aws#180]
### Expected behavior
Be able to share a specific volume beetween stacks or specify the EFS directory name where volume is mounted from the docker-compose file.

### Actual behavior

[Documentation page ](https://docs.docker.com/docker-for-aws/persistent-data-volumes/#share-the-same-volume-among-tasks-using-efs) describes how to do that manually creating and mounting the volume from the command line, I've not found the details about how to do the same using docker-compose syntax.

### Information

  - Documentation page abut volumes: https://docs.docker.com/docker-for-aws/persistent-data-volumes/
  - Using [Portainer](https://portainer.io/) to create and manage stacks
  - Docker version: 17.12.0-ce, build c97c6d6

### Steps to reproduce the behavior

  1. create a stack A
```yml
version: "3.4"
services:
    web:
      image: "myimage:production"
      volumes:
            - 'shared:/shared'
      deploy:
            mode: replicated
            replicas: 4
            update_config:
                order: start-first
            placement:
                constraints: [node.role == worker]
volumes:
    shared:
        driver: 'cloudstor:aws'
```

  2. create a stack B
```yml
version: "3.4"
services:
    web:
      image: "myimage:develop"
      deploy:
            mode: replicated
            replicas: 1
            update_config:
                order: start-first
            placement:
                constraints: [node.role == worker]
```
 3. (missing step) mount the `shared` volume from stack A to stack B
