### ISSUE TITLE
invalid mount config for type "bind" : host is down

### ISSUE THREAD

**Issue by xinbinhuang** [docker/for-aws#199]
### Expected behavior
Launch the service with `docker-compose up`. 

### Actual behavior
Cannot launch the services. Error: `invalid mount config for type "bind" : host is down`

### Information

Actual compose file
```
version: '2.3'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        # volumes:
        #     - type: volume
        #       source: metadata
        #       target: /var/lib/postgresql/data
        #       volume:
        #         nocopy: true

    webserver:
        image: <private-registry>/airflow:latest
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - type: bind
              source: ./dags
              target: /usr/local/airflow/dags
            - type: bind
              source: ./jobs
              target: /usr/local/airflow/jobs
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

volumes:
    metadata:
```
### Steps to reproduce the behavior

  1. ...
  2. ...
