### ISSUE TITLE
How to change permission to Cloudstor volume

### ISSUE THREAD

**Issue by gang89** [docker/for-aws#206]
I am currently trying to deploy Graylog with a cloudStor volume attached to graylog_journal.

The graylog service refuse to start due to permission error.

Graylog currently runs with user Id 1100. How do i set the volume permission to allow for user 1100 to access the cloudStor volume?

**Error Message from docker**
```
ERROR: Unable to access file /usr/share/graylog/data/journal/graylog2-committed-read-offset: Permission denied
```
**Partial Docker Compose file**
```
graylog:
    image: graylog/graylog:3.1
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://url:90/
      # Elastic Settings
      - GRAYLOG_ELASTICSEARCH_HOSTS=https://url.amazonaws.com/
    depends_on:
      - mongo
    networks:
      - graylog_network
    ports:
      # Graylog web interface and REST API
      - "90:9000"
      # Syslog TCP
      - "1514:1514"
      # Syslog UDP
      - "1514:1514/udp"
      # GELF TCP
      - "12201:12201"
      # GELF UDP
      - "12201:12201/udp"
    deploy:
        placement:
            constraints:
                - node.hostname == ip-172-31-21-7.ap-southeast-1.compute.internal

# Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
  mongo_store:
    external: true
  graylog_journal:
    external: true
```
