### ISSUE TITLE
stack deploy causes nodes to randomly fail health checks making the stack unusable

### ISSUE THREAD

**Issue by grigored** [docker/for-aws#66]
### Expected behavior
I followed the getting started guide and deployed a docker swarm a few months ago. There were a few hiccups, but `docker stack deploy --compose-file docker-compose.yml stack --with-registry-auth` mostly worked well until June 28 (maybe it has to do with docker 17.06 being released then?). Not sure if this matters, but as per the dockerfile below, we are using the same image to launch multiple services (with different commands).

### Actual behavior
Since June 28, most (but not all!) deploys cause nodes to be randomly restarted by the ELB health check, making everything unusable.   
```
Updating service stack_service1 (id: ln6mpm5gxzxa7sn6suibr78kx)
Updating service stack_service2 (id: 00aouqsrr8sm8tvbgkuvdyyql)
Updating service stack_service3 (id: k4ze8u9mj8ppkyfphjvc4v7ez)
Updating service stack_service4 (id: v8tu2gisouxewxhvn4uoiio8r)
Updating service stack_visualizer (id: jd7wlqxdxkd74ogl9uemwfhxv)
Error response from daemon: rpc error: code = 2 desc = update out of sequence
```
Sometimes, the swarm is left with two few managers:
```
Error response from daemon: rpc error: code = 2 desc = The swarm does not have a leader. It's possible that too few managers are online. Make sure more than half of the managers are online.
```
### Information

When this first happened, we had ~1 hour of downtime and the hot fix was to just deploy a fresh swarm using the cloudformation template. But the same thing happened when we tried to update that one. We've now switched to a manual setup.

  - Full output of the diagnostics from "docker-diagnose" ran from one of the instance
```
OK hostname=ip-172-31-9-76-ec2-internal session=1500250718-yhymVrXtQdTg84WRrOWECkVXDmRYwpDx
OK hostname=ip-172-31-29-59-ec2-internal session=1500250718-yhymVrXtQdTg84WRrOWECkVXDmRYwpDx
OK hostname=ip-172-31-17-121-ec2-internal session=1500250718-yhymVrXtQdTg84WRrOWECkVXDmRYwpDx
OK hostname=ip-172-31-42-178-ec2-internal session=1500250718-yhymVrXtQdTg84WRrOWECkVXDmRYwpDx
curl: (7) Failed to connect to 172.31.42.169 port 44554: Connection refused
OK hostname=ip-172-31-41-135-ec2-internal session=1500250718-yhymVrXtQdTg84WRrOWECkVXDmRYwpDx
Done requesting diagnostics.
Your diagnostics session ID is 1500250718-yhymVrXtQdTg84WRrOWECkVXDmRYwpDx
```

Please provide this session ID to the maintainer debugging your issue.
  - A reproducible case if this is a bug, Dockerfiles FTW
docker-compose.yml
```
version: "3"
services:
  service1:
    image: user/same_repo
    networks:
      - webnet
    ports:
      - "443:443"
    logging:
      driver: "json-file"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    command: gunicorn -c app/src/wsgi/gunicorn_conf.py app.src.wsgi.wsgi:app

  service2:
    image: user/same_repo
    networks:
      - webnet
    ports:
      - "8001:8001"
    logging:
      driver: "json-file"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    command: gunicorn -c app/jobs/wsgi/gunicorn_conf.py app.jobs.wsgi.wsgi:app

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

  service3:
    image: user/other_repo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    logging:
      driver: "json-file"
    networks:
      - webnet
    ports:
      - "7001:7001"
      - "6000:6000"
      - "6001:6001"

networks:
  webnet:
```
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...
