### ISSUE TITLE
Cloudstor Plugin Disabled in Fresh Stable Install

### ISSUE THREAD

**Issue by RehanSaeed** [docker/for-aws#85]
### Expected behavior

Use Docker for AWS 17.06 stable channel to do a fresh install in the Ireland AWS region. Expect to see AWS Cloudstor plugin installed and enabled.

### Actual behavior

Plugin is installed but disabled. Enabling it causes the following error:

> Error response from daemon: dial unix /run/docker/plugins/038e08d3f72ba67503691db2521ba669711f930df5d4a3afd9664b915038f2de/cloudstor.sock: connect: no such file or directory

### Information

  - Full output of the diagnostics from "docker-diagnose" ran from one of the instance

`docker-diagnose` produces no output. Does it log to a file?

### Steps to reproduce the behavior

  1. Use Docker for AWS 17.06 stable channel to do a fresh install in the Ireland AWS region
  2. `docker plugin ls`

### Side Question

I just want to confirm that the syntax used to talk to an EBS/EFS volume is correct. So this means that Docker has access to create or delete EBS/EFS volumes for me.

```
version: '3.3'

services:
  artefacts:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - artefacts:/nexus-data

volumes:
  artefacts:
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      ebstype: gp2
      size: 100
```
